spring :
  application :
    name : property-access-service
    
  config :
    import : optional:configserver:http://localhost:8888
    
  profiles :
    active : dev
    
server :
  port : ${port:8100}
  
management :
  endpoints :
    web :
      exposure :
        include : refresh
   
   
